---
spring:
  profiles: dev
  application:
    sex: man
    age: 48
    name: microservicecloud-config-atguigu-dev
    
---

spring:
  profiles: test
  application:
     name: microservicecloud-config-atguigu-test
     #必须保存为UTF-8格式
